---
- name: Postgresql
  hosts: postgresql
  become: yes
  remote_user: ubuntu
  become_method: sudo
  tasks:
    - name: Deploy PostgreSQL
      include_role:
        name: my_postgres_role

    - name: Add backup script to cron
      cron:
        name: "Create backup cron"
        minute: "0"
        hour: "0"
        job: "{{ pg_backup_script_path }}/backup_script.sh"

