---
- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: pg_hba.yml
- include_tasks: users.yml
- include_tasks: databases.yml
- include_tasks: users_privs.yml
- include_tasks: backup.yml